package com.pm.billingservice.grpc;

import io.grpc.stub.StreamObserver;
import net.devh.boot.grpc.server.service.GrpcService;
import billing.BillingServiceGrpc.BillingServiceImplBase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * ============================================================================
 * gRPC SERVICE IMPLEMENTATION (SERVER SIDE)
 * ============================================================================
 *
 * This class implements the gRPC server for the Billing Service.
 * It listens for incoming gRPC requests from clients (like the Patient Service).
 *
 * @GrpcService ANNOTATION:
 * -------------------------
 * Provided by the 'grpc-spring-boot-starter' library. It acts exactly like
 * Spring's standard @Service or @RestController, but specifically for gRPC.
 * It registers this class as a gRPC service bean and automatically binds it
 * to the gRPC server port (default 9090, but we configured 9001).
 *
 * EXTENDING BillingServiceImplBase:
 * ---------------------------------
 * BillingServiceImplBase is a class AUTO-GENERATED by the Protobuf compiler
 * from our billing-service.proto file. It contains empty methods for every
 * 'rpc' defined in the proto file. We OVERRIDE these methods to provide
 * the actual business logic.
 */
@GrpcService
public class BillingGrpcService extends BillingServiceImplBase {
    private static final Logger log = LoggerFactory.getLogger(BillingGrpcService.class);

    /**
     * CREATE BILLING ACCOUNT - RPC METHOD
     * -----------------------------------
     * This method handles the 'CreateBillingAccount' RPC defined in the proto file.
     *
     * WHY `StreamObserver` INSTEAD OF A NORMAL RETURN TYPE?
     * -----------------------------------------------------
     * In REST, a method returns a Response object directly.
     * In gRPC, communication is ASYNCHRONOUS and can be STREAMING.
     * The `StreamObserver` allows us to push responses back to the client.
     * 
     * Even though this is a Unary RPC (1 request, 1 response), gRPC still uses
     * the StreamObserver pattern.
     *
     * @param billingRequest The incoming request payload (auto-generated Java object)
     * @param responseObserver The channel used to send the response back to the client
     */
    @Override
    public void createBillingAccount(billing.BillingRequest billingRequest,
                                     StreamObserver<billing.BillingResponse> responseObserver){
        
        log.info("createBillingAccount request received: {}", billingRequest.toString());

        // ==========================================
        // BUSINESS LOGIC GOES HERE (Simulated)
        // ==========================================
        // In a real application, you would:
        // 1. Verify the patient exists (maybe via DB)
        // 2. Create a new BillingAccount entity
        // 3. Save it to the PostgreSQL database
        // 4. Return the generated Account ID
        // ==========================================

        // Creating the response using the Protobuf auto-generated Builder pattern.
        billing.BillingResponse response = billing.BillingResponse.newBuilder()
                .setAccountId("12345")
                .setStatus("ACTIVE")
                .build();

        // Send the response object back to the client
        responseObserver.onNext(response);
        
        // Signal that we are done sending data. The connection for this call
        // can now be safely closed. (Critical step!)
        responseObserver.onCompleted();
    }
}
